### ISSUE TITLE
Formulierungen bei Wahrheitstabellen-Füllen-Aufgabe

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#10]
Hier: 
![image](https://user-images.githubusercontent.com/5853832/139535073-69620d82-d7da-4c98-9c2d-28a943a48282.png)
wäre vielleicht sinnvoll, die Ausgabe von "in konjunktiver Normalform" durch den Aufgabensteller abschaltbar zu machen. Also beim Einstellen der Aufgabe kann man entscheiden, ob diese Information ausgegeben werden soll oder nicht. Denn wenn in der Vorlesung zu dem Zeitpunkt über "KNF" noch nichts gesagt wurde, könnte das diese Ausgabe eher verwirrend sein.

(Eventuell könnte auch immer auf diese Ausgabe verzichtet werden. Für das Ausfüllen der Wahrheitstafel spielt es ja keine große Rolle, dass/ob die Formel in einer Normalform vorliegt.)

**Comment by jvoigtlaender** [comment]
Hier: 
![image](https://user-images.githubusercontent.com/5853832/139535218-09cddb01-b55b-47fa-9ed9-a60c32114c11.png)
sind die Bezüge nicht unbedingt klar. Man soll nur die fehlenden Werte eingeben. Aber dann ist von "der ersten Zeile" die Rede. Ist damit wirklich die erste Zeile der Wahrheitstafel gemeint oder die erste Zeile mit einem fehlenden Eintrag?

Dieser mögliche Zweifel sollte am besten bereits durch die Aufgabenformulierung ausgeräumt werden.

**Comment by jvoigtlaender** [comment]
Obiger "Zweifel" wird im konkreten Fall auch dadurch genährt, dass darunter steht: 
![image](https://user-images.githubusercontent.com/5853832/139535335-9867472c-4f78-4fb7-a17d-c8420899c8e6.png)
Da ist nun als Beispiel eine Liste mit vier Elementen gegeben. Da könnte man meinen, dass also doch alle vier Werte der letzten Spalte angegeben werden sollen, im Gegensatz zu weiter oben "Liste der fehlenden Wahrheitswerte".

Auch hier sollte durch Umformulierung gegengesteuert werden. Zum Beispiel "Ein Lösungsversuch im Fall von vier Lücken könnte beispielsweise so aussehen: [f,w,w,w]".

(Oder andere geeignete Anpassung.)

**Comment by jvoigtlaender** [comment]
Typo: "Negtion"

**Comment by jvoigtlaender** [comment]
Im Feedback ist auch noch die Punktuation falsch: 
![image](https://user-images.githubusercontent.com/5853832/140490719-b2e6816c-10ef-47e9-ae3c-6618bb870861.png)

**Comment by patritzenfeld** [comment]
Die Vorschläge wurden umgesetzt (der KNF-Teil der Beschreibung wurde aus allen Aufgaben entfernt, in denen er nicht relevant ist).
