### ISSUE TITLE
Formulierungen bei Wahrheitstabellen-Fehler-Aufgabe

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#11]
Hier "Fehlerhaften" lieber kleingeschrieben: 
![image](https://user-images.githubusercontent.com/5853832/140546067-5bfd23ee-e385-46fb-9672-9fd0da8e493e.png)

Hier "Indizes" statt "Indices": 
![image](https://user-images.githubusercontent.com/5853832/140546132-189f7311-93ef-4d79-b1ad-19d1c10c2699.png)

Man könnte sich als Nutzer auch fragen, wie die Indizes denn zu zählen sind. Also bei `0` beginnend oder bei `1` beginnend.

Und wenn man sich ganz naiv stellt, könnte man auch der Meinung sein, eine "fehlerhafte" Zeile könnte in einer der vorderen Spalten fehlerhaft sein, statt in der letzten. Also was wenn ich herausfinde, dass man die letzte Spalte völlig unverändert ließe, aber einfach in den vorderen Spalten etwas tauscht? (Aber so, dass immer noch eine korrekte Wahrheitstafel herauskommt, in dem Sinne, dass genau alle verschiedenen Belegungen der gegebenen atomaren Formeln auftreten.)

Vielleicht sollte man diesem "naiv-stellen" durch irgendeine Formulierung noch entgegenwirken.

**Comment by patritzenfeld** [comment]
Habe die Fehler korrigiert und bzgl. der Indizes und zu prüfender Spalte die Aufgabenstellung angepasst.
