### ISSUE TITLE
Ungleichgewicht Aufgabengröße bei gleicher Konfiguration?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#12]
Zum Beispiel diese beiden Instanzen:
- https://autotool.fmi.uni-due.de/route/einsendung/3/153
- https://autotool.fmi.uni-due.de/route/einsendung/3/27

scheinen aus gleicher Konfiguration zu kommen, aber einmal waren es vier Lücken und einmal zwei Lücken.

Könnte das Problem sein, dass die `usedLiterals` nicht immer alle benutzt werden?

**Comment by jvoigtlaender** [comment]
Das tritt auch hier auf:
- https://autotool.fmi.uni-due.de/route/einsendung/181/720
- https://autotool.fmi.uni-due.de/route/einsendung/181/750

@owestphal, das müsste für die Bewertung im Auge behalten werden.

**Comment by owestphal** [comment]
6f7d1a0a2d3c3bd8556c8e4d3d66b7761e16a2b9 behebt das Problem mit `usedLiterals` und damit vermutlich auch das Ungleichgewicht in der Aufgabengröße.
