### ISSUE TITLE
Falsche Lösungsvorschläge bei Syntaxbaum-zu-Formel Übersetzungsaufgaben

### ISSUE THREAD

**Issue by adrian-s02** [fmidue/logic-tasks#134]
Bei Aufgaben, wo ein vorgegebener Syntaxbaum in eine Formel übersetzt werden soll (z.B. Task10 B, Task04 B, Task03 B), wird bei Angabe einer falschen Lösung ein falsches Feedback mit einer falschen "möglichen Lösung" ausgegeben.

Aufgabenstellung Task10 B:

![image](https://github.com/fmidue/logic-tasks/assets/131303630/f1a25329-43f8-492e-9db9-fc50f300d3ac)

Feedback:

![image](https://github.com/fmidue/logic-tasks/assets/131303630/0f8ebcba-c911-45b6-9510-1009f8a978aa)

**Comment by jvoigtlaender** [comment]
@owestphal, könnte das das gleiche Problem sein wie in https://github.com/fmidue/logic-tasks/commit/c989187cbb98ec7efc063589cee7d88c3273f85d für anderen Aufgabentyp gefixt?

**Comment by owestphal** [comment]
addressed in 8a9537b528e0981a048688b0df4f68cff07b3356
