### ISSUE TITLE
Reihenfolge der Aufgaben beachten

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#136]
die aktuelle Aufgabe 2: SuperfluousBrackets
"Aufgrund der Assoziativität von ∧ und ∨ müssen Formeln mit drei oder mehr atomaren Aussagen und den gleichen logischen Operatoren nicht geklammert werden."

die aktuelle Aufgabe 3: TreeToFormula
"Auch dürfen Sie bei dieser Aufgabe nicht Assoziativität verwenden, um Klammern einzusparen."

durch die Änderung der Reihenfolge der Aufgabenstellung von 3 wie in #135 adressiert, sollte das Problem nicht so groß sein

**Comment by jvoigtlaender** [comment]
Wird in Meta-Issue für Beobachtungen zu konkreten Aufgabenkonfigurationen nachgehalten, siehe https://github.com/fmidue/logic-tasks/issues/146#issuecomment-2199381835.
