### ISSUE TITLE
Mögliche Schreibweisen ergänzen

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#138]
Die Symbole ¬ ∨ ∧ können in der Auflistung, der möglichen Schreibweisen auftauchen.
Dadurch wird klar, dass es möglich ist diese Ausdrücke zu kopieren und dann einzufügen, ohne einen Syntaxfehler zu erhalten.

**Comment by jvoigtlaender** [comment]
Passieren tut diese Ausgabe der "Legende" in folgenden Definitionen: https://github.com/fmidue/logic-tasks/blob/8a9537b528e0981a048688b0df4f68cff07b3356/src/LogicTasks/Helpers.hs#L63-L141

Im Wesentlichen ginge es um einen Abgleich bzw. eine Übernahme der "Tokensymbole", die vom Parser tatsächlich als Eingabe akzeptiert werden, hier: https://github.com/fmidue/logic-tasks/blob/8a9537b528e0981a048688b0df4f68cff07b3356/src/UniversalParser.hs#L138-L169
