### ISSUE TITLE
Position der Bäume in ComposeFormula

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#141]
Die beiden Bäume werden so dicht nebeneinander angezeigt, sodass sie auf den ersten Blick wie ein Baum aussehen.

![grafik](https://github.com/fmidue/logic-tasks/assets/116375062/19d60a91-e199-476c-a63e-caf61fd6c1fd)

**Comment by jvoigtlaender** [comment]
Die Umsetzung könnte sein, hier: https://github.com/fmidue/logic-tasks/blob/8a9537b528e0981a048688b0df4f68cff07b3356/src/LogicTasks/Syntax/ComposeFormula.hs#L47-L55 statt die Bäume einfach kommentarlos auszugeben, expliziten Vor- und Zwischentext zu haben. Also jeweils in dem `Just`-Fall etwas wie "Hier ist der eine Baum:", "Hier ist der andere Baum:".

**Comment by KatinkaMeer** [comment]
Wenn es möglich ist, wäre ein Anzeigen der Bäume **nebeneinander** auch schön, da mann so weniger Scrollen muss, wobei das generell ein Problem ist, dass man die Aufgabe und das Abgabefeld nicht gleichzeitig auf dem Bildschirm sehen kann.
