### ISSUE TITLE
Schwierigkeitsgrad DecomposeFormula

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#142]
Vielleicht sollte die Aufgabe so konfiguriert werden (können), dass die „Mitte“ nicht so leicht zu finden ist.

`(A <= E) ∧ (D => (¬C ∨ ¬B))`
umzuschreiben zu:
`(D => (¬C ∨ ¬B)) ∧ (A <= E)`
ist Aufwand von 10 Sekunden und sehr einfach.

Bsp.:
`((A <= E) ∧ (D => (¬C ∨ ¬B))) ∨ A`
`(((A <= E) ∧ (D => (¬C ∨ ¬B))) ∨ ((A <= E) <= A)) ∧ C`

**Comment by jvoigtlaender** [comment]
Ist in diesen angegebenen Beispielen das Finden der Stelle, an der getauscht werden muss, denn wirklich schwerer? Ich kann mir die Formeln ja auch von hinten anschauen und sehe sofort, dass da ein einzelnes Literal `A` bzw. `C` steht, das direkt mit einer großen anderen Formel verknüpft ist. Da bin ich ja praktisch sogar *noch* schneller an dem Punkt, wo ich weiß was ich wie rekombinieren muss.

**Comment by KatinkaMeer** [comment]
Kann sein, bestimmt gibt es bessere Möglichkeiten. Ich bin gegen den gesamten Aufgabentyp.
