### ISSUE TITLE
Fehlender Syntaxtest bei Decide

### ISSUE THREAD

**Issue by KaroBo2409** [fmidue/logic-tasks#144]
Die Zeile "Lösung überschreitet nicht Anzahl der Zeilen" scheint nicht so richtig zu funktionieren.

Eingabe:
400 oder -10

Ausgabe in der genannten Zeile:
"Ja"

**Comment by jvoigtlaender** [comment]
Ist hier vielleicht eher die Beschreibung der Zeile missverständlich?

Mit "Lösung überschreitet nicht ..." ist hier denke ich gemeint, dass in der Lösung (als Liste) nicht mehr Elemente vorkommen sollen als es Zeilen in der Wahrheitstabelle gibt. Wenn also etwa `[400]` oder `[-10]` eingegeben wird (war das der Fall?), dann gibt es nur ein Element in der Liste und diese Anzahl ist also nicht höher als die Anzahl der Zeilen der Wahrheitstafel.

Ihre Interpretation der Aussage war aber, dass geprüft würde, ob die angegebenen Werte tatsächlich sinnvolle Zeilen der Wahrheitstafel adressieren? Das wäre wahrscheinlich eher der Job der Prüfzeile "Lösung enthält Indizes?", die das aber offenbar bisher auch nicht prüft.

**Comment by nimec01** [comment]
Ich habe mal einen Pull Request geöffnet, der die Formulierung anpasst.

**Comment by jvoigtlaender** [comment]
Okay, aber vielleicht sollte dennoch zusätzlich auch noch ein Syntaxttest eingeführt werden, dass die einzelnen Einträge der Liste sich im korrekten Bereich befinden. Also obiges:
> Das wäre wahrscheinlich eher der Job der Prüfzeile "Lösung enthält Indizes?", die das aber offenbar bisher auch nicht prüft.
