### ISSUE TITLE
Aufgabengenerierung?

### ISSUE THREAD

**Issue by KaroBo2409** [fmidue/logic-tasks#145]
Bei Aufgabe 12 A und 13 A wurde bei mir die gleiche Aufgabe generiert. Hier vielleicht ein paar mehr Varianten hinzufügen

**Comment by jvoigtlaender** [comment]
Es ist wohl in der Tat unglücklich, dass Aufgaben 12 und 13 die gleiche Konfiguration verwenden: https://github.com/fmidue/logic-tasks/blob/8a9537b528e0981a048688b0df4f68cff07b3356/examples/src/Semantics/Resolution/Step/Config.hs#L12-L26 insbesondere beide `minClauseLength = maxClauseLength = 2`. Eine der beiden sollte wohl komplexer sein (wobei bereits `task14` den naheliegenden Fall `minClauseLength = maxClauseLength = 3` enthält), oder ein anderes "Alphabet" verwenden.

Ich lege ein Meta-Issue an für Beobachtungen zu konkreten Aufgabenkonfigurationen.

**Comment by jvoigtlaender** [comment]
siehe https://github.com/fmidue/logic-tasks/issues/146#issuecomment-2199378490
