### ISSUE TITLE
Syntaxbaum zu Formel: zu schwache syntaktische Überprüfung

### ISSUE THREAD

**Issue by KaroBo2409** [fmidue/logic-tasks#148]
Nicht vorhandene Literale, die als Lösung angegeben werden, werden nicht als Fehler geworfen. (Task 4 B)

**Comment by jvoigtlaender** [comment]
Geht es darum, dass falsche Literale innerhalb einer ansonsten korrekt geformten Formel auftreten?

Können Sie ein Beispiel anfügen, was eingegeben wurde, was als Feedback kam, und was darin fehlte?

**Comment by KaroBo2409** [comment]
Ich habe zum Beispiel bei Task 03 b einfach ein Z eingegeben (was kein genutztes Literal in der Aufgabenstellung ist) und autotool hat diese Lösung akzeptiert.

**Comment by jvoigtlaender** [comment]
Oh, es geht aber nur um die syntaktische Vorprüfung, richtig? Nicht um die Bewertung der Korrektheit. Also es geht darum, dass bei der Aufgabe schon bei der Einreichung gesagt werden könnte "Z kommt gar nicht in dem Baum vor", unabhängig davon, dass bei der Bewertung auch noch rauskäme, dass die Formel inkorrekt ist. (Wohingegen bei Eingabe von A keine Vorab-Zurückweisung käme, weil A ja tatsächlich zumindest ein verwendetes Literal ist, aber später dann A dennoch als insgesamt inkorrekt vermeldet würde, da es ja nicht den ganzen Baum wiedergibt.)

Kontext: Die `b`-Aufgaben haben alle eine Einsendefrist, bis zu welcher kein inhaltliches Feedback (nur Syntaxprüfung) gegeben wird. Die jeweiligen entsprechenden `a`-Aufgaben mit ansonsten gleicher Nummer haben die gleichen Aufgabenparameter aber sofortiges auch inhaltliches Feedback.
