### ISSUE TITLE
Task 07 B

### ISSUE THREAD

**Issue by KaroBo2409** [fmidue/logic-tasks#149]
Die Knöpfe "vorherige Einsendung laden" und "letzte syntaktisch korrekte Einsendung laden" laden nur die aktuelle Lösung neu und nicht wie gedacht eine vorherige Lösung.

**Comment by jvoigtlaender** [comment]
Ist das spezifisch für diese eine genannte Aufgabe (bzw. deren Aufgabentyp), oder tritt das über alle Aufgaben hinweg auf?

Im letzteren (wahrscheinlicheren?) Fall wäre es ein allgemeines Autotool-Problem und besser als Issue bei https://git.uni-due.de/fmi/autotool-dev/-/issues aufgehoben.

**Comment by KaroBo2409** [comment]
nein das ist nicht bei allen Aufgaben. Allerdings ist mir das Problem in ein paar Propa Aufgaben auf autotool auch schon aufgefallen.

**Comment by jvoigtlaender** [comment]
Hmm, vielleicht dann dennoch lieber ein allgemeines Issue im Autotool-Repo und dann ein paar konkrete Fälle dokumentieren, bei denen das auftritt. Die Unterschiede zwischen dem Auftreten (oder nicht) bei verschiedenen Aufgaben können fast nur an irgendwelchen Einstellungen liegen, durch die gesteuert wird, wann syntaktisches und wann semantisches Feedback gegeben wird, und in welchen Fällen eine Lösung abgespeichert wird, um sie wieder aufrufen zu können.

Verschiedene Aufgabentypen ziehen eine unterschiedliche Trennlinie zwischen "syntaktischer Test" und "semantischer Test". Wenn wir ein paar konkrete Fälle haben, wo das Nachladen entweder funktioniert oder nicht funktioniert, können wir vielleicht ableiten, bei welchen Einstellungen/Konstellationen es hapert.

**Comment by KaroBo2409** [comment]
Ich habe nun zumindest herausgefunden, dass bei allen Aufgaben (aus dem A Teil) der Knopf "vorherige Einsendung laden" nur funktioniert, wenn man als aktuelle Lösung die richtige Lösung hat. Dann wird die letzte (in meinem Testfall falsche) Lösung geladen.
Hat man jedoch eine falsche Lösung aktuell stehen und hatte beispielsweise vorher eine richtige Lösung, lädt der Knopf die aktuelle Lösung nur neu und eben nicht die vorherige korrekte. 

Der Knopf "letzte syntaktisch korrekte Einsendung laden" hat bei mir in jeder Aufgabe (aus dem A Teil) immer nur die aktuelle Lösung neu geladen, auch wenn diese syntaktisch falsch war und vorher eine syntaktisch richtige Lösung abgegeben wurde.

**Comment by jvoigtlaender** [comment]
Hoffen wir mal, dass das Autotool-seitig verbessert wird. Hier lokal lässt sich das zumindest nicht direkt adressieren.
