### ISSUE TITLE
LogicResolutionComplete "zerschießt" Autotool

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#151]
Wird zu einer Aufgabeninstanz eine vollständige Lösung eingereicht, ist alles gut.

Entfernt man daraus jedoch den letzten Schritt, dann scheint sich Autotool aufzuhängen, also liefert kein Feedback etc.

Der erste Schritt zur Diagnose wäre wohl, auszuprobieren, was bei lokaler Ausführung passiert. (Es könnte sein, dass da eine Endlosschleife läuft, welche auf Autotool irgendwann in einen Timeout gerät.)

**Comment by owestphal** [comment]
Das Problem scheint `showSolution = True` zu sein. Das berechnen einer möglichen Lösung dauert wohl zu lange. Wenn die Lösung korrekt ist, wird keine Lösung zum Anzeigen berechnet, daher  gibt es dann auch kein Problem.

**Comment by jvoigtlaender** [comment]
Eine Anschlussfrage ist dann wohl, warum die jeweilige Musterlösung überhaupt erst nach dem Einreichen berechnet wird. Sie hängt ja nicht vom eingegebenen Lösungsversuch ab. Also die Berechnung von `computeResSteps clauses` hier: https://github.com/fmidue/logic-tasks/blob/1a2da64253cc0c85ea6bc8cdf14642cc411dda55/src/LogicTasks/Semantics/Resolve.hs#L247 könnte ja bereits hier stattfinden: https://github.com/fmidue/logic-tasks/blob/1a2da64253cc0c85ea6bc8cdf14642cc411dda55/src/LogicTasks/Semantics/Resolve.hs#L54-L60

Dann würde das nur ein Mal pro Instanz passieren statt bei jeder Lösungseingabe. Und eventuell ist das auch eine Stelle, wo ein weniger strenger Timeout (oder gar keiner?) gesetzt ist.

**Comment by owestphal** [comment]
Letztlich muss das auch gar nicht separat berechnet werden. Die Lösung sollte ja eigetlich mehr oder weniger direkt im Generator bereits erstellt worden sein.

**Comment by jvoigtlaender** [comment]
ersetzt durch #152 und #153
