### ISSUE TITLE
widersprüchliche Beispielsangabe

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#16]
Da steht, man könne `f, w` als Abkürzung für Wahrheitswerte verwenden, aber das angegebene Beispiel verwendet `t` statt `w`: 

![image](https://user-images.githubusercontent.com/5853832/201644662-7a183ca0-f72e-47b7-aae4-15dba6144bd8.png)

**Comment by patritzenfeld** [comment]
Das Beispiel verwendet jetzt 0 und 1, damit es mit beiden Sprachen funktioniert.
