### ISSUE TITLE
Unterscheidung zwischen syntaktischen und semantischen Fehlern

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#17]
Die Aufgaben machen aktuell keinen Gebrauch von Autotools Möglichkeit, Fehler als syntaktisch oder semantisch zu klassifizieren. Insbesondere wenn die Bewertung der Aufgaben erst nach der Bearbeitungszeit angezeigt wird, verhindert das, dass Studierende frühzeitig auf syntaktische Fehler in der Eingabe hingewiesen werden.

**Comment by patritzenfeld** [comment]
Wird durch anstehenden merge in autotool-all erledigt.
