### ISSUE TITLE
Weniger strenge Bewertungen

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#18]
Möglicherweise sollten auch Einsendungen wie die folgende akzeptiert werden: 
![image](https://user-images.githubusercontent.com/10613418/202150271-51414604-9be1-4f36-8111-ecb445eececd.png)
Insbesondere solange #17 offen ist.

**Comment by patritzenfeld** [comment]
Wie ist das gemeint? Sollen bei zu langen Abgaben einfach die überschüssigen Stellen ignoriert werden?

**Comment by jvoigtlaender** [comment]
Nein, ich denke es war gemeint, dass neben "richtige Anzahl gemäß der Lücken" auch (und einzig noch) der Fall "es wurde einfach die gesamte letzte Spalte angegeben" akzeptiert werden soll.

Also:
- wenn "Länge der eingegebenen Liste = Anzahl der Lücken", dann Bewertung wie aktuell
- wenn "Länge der eingegebenen Liste = 2^(Anzahl atomarer Aussagen)", dann Vergleich der Liste zur korrekten Liste mit sowohl den sowieso vorgegebenen Werten als auch den richtigen Werten für die Lücken
- in jedem anderen Fall, als Syntaxfehler ansehen (bzw. so verfahren wie aktuell schon verfahren wird, wenn nicht genau so viele Werte eingegeben werden wie es Lücken gibt)
