### ISSUE TITLE
mehr vom Erklärtext der ComposeFormula-Aufgaben anpassen oder weglassen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#197]
Auch mit `inputHelp = False` wird dort immer noch von Listen geredet: https://github.com/fmidue/logic-tasks/blob/9fa5e730d20d1e226c6ecce29b5d485a51f05492/src/LogicTasks/Syntax/ComposeFormula.hs#L64-L68
Das könnte einige Studierende verwirren, weil in der Flex-Task-Ausführung gar keine Listen auftreten, sondern einfach zwei separate Eingabefelder.

**Comment by patritzenfeld** [comment]
Das gleiche auch bei der SubFormula aufgabe mit mehreren Eingabefeldern

**Comment by jvoigtlaender** [comment]
> Das gleiche auch bei der SubFormula-Aufgabe mit mehreren Eingabefeldern.

Konkret dort finde ich keine Veränderung nötig. Es ist auch kurz von einer Liste die Rede, aber die konkrete Formulierung passt auch zu Eingabe über mehrere Felder. Und ich habe sogar in der aktuell laufenden Aufgabe im Kurs bewusst einen extraText verwendet, der sich auf die Nennung der Liste bezieht.
