### ISSUE TITLE
Bewertung von Min-Quiz defekt?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#20]
Es kommt immer
```
Alle Konjunktionen sind Minterme?<blockquote><pre>Nein.</pre></blockquote>
```
selbst wo Minterme vorzuliegen scheinen.

**Comment by patritzenfeld** [comment]
In dem Check fehlte eine Negation.

**Comment by jvoigtlaender** [comment]
@owestphal, dann muss mit dem korrigierten Code eine Neubewertung der bereits abgegebenen Autotool-Einreichungen durchgeführt werden.
