### ISSUE TITLE
Zurückweisen von "zu wenig geklammerten" `PropFormula`s

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#224]
> Vielleicht sollte für den Moment die Erwartung eher sein:
> `fromRight (Atomic 'X') $ parse parser "" "A /\\ B => C"`
> führt zu Error?

_Originally posted by @jvoigtlaender in https://github.com/fmidue/logic-tasks/issues/150#issuecomment-2258506505_

**Comment by jvoigtlaender** [comment]
Das Issue dort wurde "completed", aber das betraf einen anderen Aspekt als den aus dem Kommentar? @owestphal 

Also dieses `A /\ B => C` wird weiterhin akzeptiert, obwohl es im Kontext der Vorlesung "nicht erlaubt" ist?

**Comment by jvoigtlaender** [comment]
Ein temporärer Fix, auch im Kontext der "Konzert-Aufgabe" könnte das ebenso bereits in besagtem Issue Gesagte sein:
>  (Es bestünde natürlich die Möglichkeit, es dann nochmal als `(A /\\ B) => C` auszugeben, als Teil der Syntax-Vorabprüfung, und Studierende könnten dann merken, dass sie Klammern nutzen müssten, wenn sie mit `A /\\ B => C` eigentlich `A /\\ (B => C)` meinten.)

**Comment by jvoigtlaender** [comment]
Als was *wird* denn `A /\ B => C` eigentlich konkret geparset? Kommt da ein `PropFormula`-Wert mit oder ohne `Brackets`-Konstruktor raus?

**Comment by patritzenfeld** [comment]
`(Assoc Impl (Assoc And (Atomic 'A') (Atomic 'B')) (Atomic 'C'))`

Also ohne Klammern.

**Comment by jvoigtlaender** [comment]
Okay, das ist inhaltlich ja irgendwie falsch, unter anderem da `Impl` gar kein assoziativer Operator ist. Da muss also geeignet drumrumgearbeitet werden.

**Comment by jvoigtlaender** [comment]
Um eine `PropFormula` mit "zusätzlichen" Klammern auszugeben, könnte wohl https://github.com/fmidue/logic-tasks/blob/5000317dd4397b69121b68838eaa72eb3d453ede/src/Trees/Types.hs#L97-L100 verwendet werden, dann `display` oder `simplestDisplay`.

**Comment by jvoigtlaender** [comment]
Wenn nötig, ließe sich damit wohl auch Herausfinden/Zurückweisen, wenn Studierende Klammern weggelassen haben, die im Kontext von Komedia nicht weggelassen werden dürften:
- `String` als `PropFormula` parsen
- `toTree` auf die `PropFormula` anwenden
- `simplestDisplay` auf den `SynTree` anwenden
- mit originalem `String` vergleichen

**Comment by owestphal** [comment]
> Das Issue dort wurde "completed", aber das betraf einen anderen Aspekt als den aus dem Kommentar? @owestphal
> 
> Also dieses `A /\ B => C` wird weiterhin akzeptiert, obwohl es im Kontext der Vorlesung "nicht erlaubt" ist?

Die Änderungen, mit denen ich die Issue geschlossen hatte, haben einfach die vorher nicht korrekt berücksichtigten Textbuch Präzedenzen korregiert. Das Verhalten ist also zu dem geworden was auch im ersten Kommentar aus #150 steht: 

> 
> `fromRight (Atomic 'X') $ parse parser "" "A /\\ B => C"`
> 
> Erwartung: `Assoc Impl (Assoc And (Atomic 'A') (Atomic 'B')) (Atomic 'C')`
> 
> Tatsächliches Resultat: `Assoc And (Atomic 'A') (Assoc Impl (Atomic 'B') (Atomic 'C'))` (enspricht `A /\\ (B => C)`)

Jetzt kommt bei Eingabe von "A /\ B => C" das zu erwartende `(A /\ B) => C` raus.
Eine spezielle Behandlung die zu einem Fehler führt hatte ich da nicht eingebaut, insofern ist der Teil quasi offen geblieben.

**Comment by jvoigtlaender** [comment]
Ersetzt durch https://github.com/fmidue/logic-tasks/issues/221#issuecomment-2487676385
