### ISSUE TITLE
`showSolution` hat keinen Effekt bei `Resolve`

### ISSUE THREAD

**Issue by patritzenfeld** [fmidue/logic-tasks#231]
Die Lösung kann nie angezeigt werden, da dafür [eine leere Klausel als Resolvente in einem Schritt eingetragen sein muss](https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Resolve.hs#L275C1-L285C57).
In `partialGrade' `wird aber schon abgebrochen, wenn [die Einzelschritte keinen Sinn ergeben und der letzte Schritt nicht die leere Klausel resolviert](https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Resolve.hs#L204-L218). 

Wenn die leere Klausel also in der Abgabe enthalten ist und man bis nach `completeGrade' `kommt, dann ist die Lösung richtig. Ansonsten wird man diese Stelle nicht erreichen und die Lösung wird auch nicht angezeigt.

**Comment by jvoigtlaender** [comment]
Stimmt diese Beobachtung auch dann, wenn `printFeedbackImmediately = False` gesetzt ist?

Also sollte einfach nur dafür gesorgt werden, dass niemals gleichzeitig  `printFeedbackImmediately = True` und `showSolution = True`?

**Comment by patritzenfeld** [comment]
Ja das stimmt. Dann passe ich die Config-Validierung an, so dass nicht beides `True` sein kann.
