### ISSUE TITLE
configure spell check linter (https://github.com/check-spelling/check-spelling)

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#26]
... so that lines in the code starting with `german` get ignored. That should resolve many of the flagged occurrences.

**Comment by patritzenfeld** [comment]
is now done, but I'm still unsure how to handle shortened names like 'maxlen' being flagged. Adding all of them to exceptions or writing them out does not seem ideal.

**Comment by jvoigtlaender** [comment]
In other repos we have indeed moved to names like `maxLength` in such situations.

**Comment by jvoigtlaender** [comment]
Another thought (you are probably already aware of): Many German text is still "hiding" in snippets like this: https://github.com/fmidue/logic-tasks/blob/58cd511cadc7b81563ab7ec8ec2854a8898c2a2a/src/LogicTasks/Syntax/IllegalCnfs.hs#L17-L19

To capture those as well via the `german`-pattern exception, there is probably no way around inlining `instruct` and `bilingual` everywhere.

**Comment by jvoigtlaender** [comment]
This:
> should I use a 'do not check marker' in a line comment

sounds like a good idea. Also in order to get to grips with how this local exception mechanism works, since we might need it in other repos as well.

**Comment by patritzenfeld** [comment]
as of commit d1c644b51c146afa3ec608ac2c9f5f6ebf5ff7f4 the spell checker is succeeding
