### ISSUE TITLE
backwards implication operator

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#29]
In various task types, `<=` could be allowed/created/handled in addition to `=>`.

**Comment by jvoigtlaender** [comment]
This should consist of touching (around) these lines:
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/Trees/Types.hs#L23
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/Trees/Types.hs#L29-L30
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/Trees/Types.hs#L61-L62
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/Trees/Print.hs#L15-L16
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/LogicTasks/Helpers.hs#L129-L134
- https://github.com/fmidue/logic-tasks/blob/2a963e511585edf72ecae02abf875744b959b518/src/Tasks/LegalCNF/GenerateIllegal.hs#L89

and probably stuff in various parser modules.

**Comment by nimec01** [comment]
Are there any preferences on how the `BinOp` data type should be changed? It's obvious that we need to add another constructor, however I'm unsure about the naming. One option that comes to my mind is to replace `Impl` with `RightArrow` and add `LeftArrow` (similar to how this works in LaTeX).
