### ISSUE TITLE
Verständlichkeit Fehlerhinweise: Index existiert nicht

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#45]
Bezogen auf z.B.: https://github/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Decide.hs#L70-L79
(aber auch in: Fill)

(kann sein, dass ich hier nicht verstehe, worauf sich die Hinweise beziehen, aber falls doch, dann:)

aus "Mindestens ein gegebener Index ist zu hoch." geht nicht zwangsläufig hervor, dass ein angegebener Index höher ist, als der höchste existierende Index

aber vor allem: aus "Mindestens ein gegebener Index ist null oder negativ."  geht nicht hervor, dass genau das, das Problem ist, es auch konträr interpretiert werden im Sinne von: "min. ein Index muss null oder negativ sein"

Vorschlag: für beide: "Mindestens einer, der angegebenen Indices existiert nicht." oder "Mindestens ein Index liegt außerhalb der Reichweite möglicher Indices: 1 - [Länge atomics cnf]."

**Comment by jvoigtlaender** [comment]
Good catch. Ich wäre für etwas wie: "Mindestens einer der angegebenen Indizes existiert nicht."

**Comment by KatinkaMeer** [comment]
#51
