### ISSUE TITLE
Verständlichkeit Fehlerhinweise: "Formel"

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#46]
bezüglich: https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Decide.hs#L65-L66
(ebenso in: Fill, Max, Min)

wie wäre eine alternative Formulierung wie: "nicht leeren Ausdruck", da es ja genau nicht darum geht eine (aussagenlogische) Formel o.Ä. anzugeben, sondern einen Index.

so auch in hier: https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Pick.hs#L64-L65

"die Liste der Formeln" (gemeint: die Nummer der passenden Tabelle), wobei ergänzend hinzukommt, dass der Plural der Formulierung suggeriert, dass zu der aussagenlogischen Formel mehrere passenden "Formeln" (gemeint: Tabellen) gibt.

**Comment by jvoigtlaender** [comment]
Hier bin ich mir nicht sicher.

Zum ersten Punkt: ich denke, da bezieht sich das wirklich auf eine Formel, nicht auf den Index einer Formel.

Allgemeiner: Gibt es einen konkreten Kontext (bei Ausführung der Aufgabe), in dem Studierende mit den genannten Texten in Berührung kommen?

Ich vermute nämlich, dass die `verifyStatic`-Meldungen gar nicht an Studierende ausgespielt werden, sondern "nur" an Lehrende. Dennoch können sie natürlich verbessert werden wo angebracht. Aber es macht dennoch einen gewissen Unterschied.

Vermutlich kann @patritzenfeld hier zur Klärung beitragen.

**Comment by patritzenfeld** [comment]
Ja, die `verifyStatic`- und `verifyQuiz`-Meldungen werden nur angezeigt, wenn man als Lehrender die Konfiguration "unsinnig" einstellt. Ein Student bekommt diese Meldungen nicht angezeigt.

**Comment by KatinkaMeer** [comment]
Was bekommen die Studierenden dann überhaupt als Feedback angezeigt?

**Comment by patritzenfeld** [comment]
@KatinkaMeer Alles was in `partialGrade` und `completeGrade` steht. Dabei wird immer zuerst `partialGrade` ausgeführt und `completeGrade` nur wenn `partialGrade` ohne Meldung durchgelaufen ist.

**Comment by KatinkaMeer** [comment]
Gibt es eine Möglichkeit, dieses Feedback auszuprobieren?
Wenn ja, wie mache ich das?

**Comment by jvoigtlaender** [comment]
Als Kontext @patritzenfeld: Ich hatte @KatinkaMeer bereits gezeigt, wie sich die Aufgabentexte anzeigen lassen, also Stack-Installation plus Aufrufe wie:
```shell
stack repl --> danach öffnet sich eine "neue Kommandozeile innerhalb eines Haskell-Interpreters", alles folgende wird dort drin eingetippt, aber mit ":q" kämen Sie da wieder heraus
> :m + Control.Monad.Output
> :m + Test.QuickCheck
> generate (generateLegalCNFInst defaultLegalCNFConfig) >>= \inst -> LogicTasks.Syntax.IllegalCnfs.description inst `withLang` German
```
Vielleicht lässt sich auf dieser Ebene/Grundlage auch erklären, wie `partialGrade` und `completeGrade` interaktiv ausprobiert werden können.

Ansonsten bestünde mittlerweile prinzipiell auch wieder die Möglichkeit, Dinge direkt in Autotool auszuprobieren. Das hängt natürlich davon ab, ob gerade die aktuellsten Aufgabenimplementierungen aus diesem Repo dort bereits eingebunden sind, und eventuell auch von noch vorhandenen "ZIM-verursachten Hängern" bei einzelnen Autotool- (vor allem Administrations-) Funktionalitäten. Das wäre dann mal noch mit @marcellussiegburg abzuklären.

**Comment by patritzenfeld** [comment]
@KatinkaMeer Um die Lösungsauswertung in der Konsole anzusehen würde ich folgendes vorschlagen (bsp. für Decide):

``` 
stack repl
> :m + Control.Monad.Output
> :m + Test.QuickCheck
> inst <- generate $ genDecideInst dDecideConf                           --> konkrete Instanz auswürfeln und einen Namen geben
> LogicTasks.Semantics.Decide.description inst  `withLang` German        --> Aufgabentext anzeigen lassen
> LogicTasks.Semantics.Decide.partialGrade inst [1,4] `withLang` German  --> Lösung (hier [1,4]) syntaktisch auswerten lassen
> LogicTasks.Semantics.Decide.completeGrade inst [1,4] `withLang` German --> Lösung (hier [1,4]) semantisch auswerten lassen
```

Die Aufgaben haben aber alle verschiedene Lösungstypen. Am besten vorher in die Datei schauen und den Typen der `start`-Funktion ansehen. Das ist der gleiche Typ wie der der Lösungseingabe.
