### ISSUE TITLE
Einheitlichkeit ähnlicher Aufgaben

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#47]
Bei den Aufgaben:
https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Prolog.hs
und Resolve.hs, soll jeweils resolviert werden. 

Einmal ist das Abgabeformat: (literal, resolvent) und das andere Mal: (first clause, second clause, resolvent)

Möchte man das vereinheitlichen?

**Comment by nimec01** [comment]
Ich sehe bei den beiden genannten Aufgaben keinen Sinn das zu vereinheitlichen. Schließlich erfüllen `Prolog` (und `Step`) einen anderen Zweck als `Resolve`. Bei letzterem soll eine vollständige Resolution geübt werden, wohingegen bei `Prolog` und `Step` ein einziger Resolutionsschritt geübt wird. Bei `Prolog` und `Step` werden daher sowieso immer nur zwei Klauseln angezeigt. Wenn man nun das Abgabeformat zu `(first clause, second clause, resolvent)` ändert, ist diese Aufgabe eventuell zu einfach oder erfüllt nicht mehr den ursprünglichen Sinn.

Sehe ich das so richtig? @jvoigtlaender
