### ISSUE TITLE
Ascii basierte Formel

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#48]
bzgl. https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Max.hs#L42-L44 undebenso in Min.hs und Step.hs

"als ascii-basierte Formel" finde ich verwirrend, klingt auf dem ersten Blick nach "etwas dass man nicht kennt, also vielleicht nicht kann", also als ob das irgendeine inhaltliche Bedeutung hätte.

Wieso nicht stattdessen einfach nur den Hinweis auf die Legende, also welche Notation zu nutzen ist.
Würde das nicht reichen?

**Comment by jvoigtlaender** [comment]
Ja, bin für so eine Änderung. Wenn Sie einen Pull Request dazu machen, können Sie einen Screenshot/Print-Ausgabe einer konkreten Aufgabeninstanz mit dem angepassten Text posten?

**Comment by KatinkaMeer** [comment]
Kann ich, wenn ich herausfinde, was ich eingeben muss, um mir diese Aufgaben anzeigen zu lassen.

**Comment by jvoigtlaender** [comment]
Der prinzipielle Weg zur Anzeige von Aufgabeninstanzen hatte aber funktioniert? (https://fmidue.slack.com/archives/D037G7LU3UJ/p1681458156024179)

Also ist das Problem bei weiteren Aufgabentypen jetzt einfach "nur", die entsprechend aufzurufenden Funktionen (in dem Slack-Beispiel eben `generateLegalCNFInst`, `defaultLegalCNFConfig` und `LogicTasks.Syntax.IllegalCnfs.description`) zu finden?

**Comment by KatinkaMeer** [comment]
ja ganau! ich habe das dahinterstehende Prinzip irgendwie nicht gesehen.. ich weiß nicht, wo ich nachschauen muss.. welche Funktionen dort stehen müssen

**Comment by jvoigtlaender** [comment]
Hmm, das ist wahrscheinlich nirgendwo exakt dokumentiert. Ich kann mal sagen, wo ich die Informationen für den "legal CNFs" Task gefunden habe. Vielleicht lässt sich das dann analog für andere Aufgaben rekonstruieren. (Aber vielleicht erfordert es auch zu viel Haskell-Interna. Dann lassen Sie das, statt daran zu "verzweifeln". Dann müssen wir eben einen anderen Weg finden, die Tasks ausprobieren zu lassen, ggfs. eben wirklich per Autotool.)

Also, es gibt ein Autotool-Repo auf GitLab. Der relevante Einstiegspunkt für die Logic-Tasks ist: https://git.uni-due.de/fmi/autotool-dev/-/tree/autotool-fmi/collection/src/Logic

Dort lässt sich durch die Unterverzeichnisse navigieren, um einen Aufgabentyp auszuwählen, zum Beispiel: `Syntax/LegalCnf.hs`

Irgendwo in der Datei steht dann `instance Partial`, und darunter was von der Art `report _ = toReporter . description`. Die darin zuletzt genannte Funktion brauchen wir schonmal. Also hier `description`. Den nötigen Prefix `LogicTasks.Syntax.IllegalCnfs` entnehmen wir dem `import LogicTasks.Syntax.IllegalCnfs` weiter oben in der Datei. (Wenn es irgendwo ein `import` gibt, das explizit `description` in Klammern enthält, dann ist jenes das richtige Modul. Ansonsten kommt nur das hoffentlich einzige `import` infrage, das irgendwie mit `Tasks` oder `LogicTasks` anfängt und keine explizite Auflistung in Klammern enthält.)

Irgendwoanders in der Datei steht `instance Generator` und darunter etwas wie `generator _ conf _ = generate $ generateLegalCNFInst conf`. Daraus entnehmen wir die Information `generateLegalCNFInst`.

Und noch an anderer Stelle in der Datei steht `make = quiz LegalCnfs defaultLegalCNFConfig`. Daraus entnehmen wir `defaultLegalCNFConfig`.

Gefunden haben wir jetzt also `LogicTasks.Syntax.IllegalCnfs.description`, `generateLegalCNFInst` und `defaultLegalCNFConfig`. Daraus können wir den benötigten Aufruf basteln:
```shell
stack repl
> :m + Control.Monad.Output
> :m + Test.QuickCheck
> generate (generateLegalCNFInst defaultLegalCNFConfig) >>= \inst -> LogicTasks.Syntax.IllegalCnfs.description inst `withLang` German
```

Die Theorie wäre nun, dass das für andere Aufgabentypen analog klappt.

**Comment by KatinkaMeer** [comment]
Auf das gitlab Repo habe ich keinen Zugriff

**Comment by KatinkaMeer** [comment]
ich kann den Inhalt des gitlab Repos leider nicht sehen

**Comment by KatinkaMeer** [comment]
Kann es sein, dass sich das gitlab Repo von dem, welches ich geklont habe, insofern unterscheidet, als dass die Aufrufe unterschiedlich sind.
Da:
`generate (genDecideInst dDecideConf) >>= \inst -> LogicTasks.Decide.description inst `withLang` German`

nicht funktioniert, stattdessen aber: 

`generate (genDecideInst dDecideConf) >>= \inst -> LogicTasks.Semantics.Decide.description inst `withLang` German`

**Comment by jvoigtlaender** [comment]
Kann sein, dass in dem GitLab repo mehrere Branches existieren, die auf verschiedene Versionen des logic-tasks repos abstellen (vor und nach einer Umorganisation des Modul-Namenraums).

**Comment by jvoigtlaender** [comment]
Der aktuell relevante Branch im Autotool-Repo ist `ude-latest-3`. Entsprechend wäre der passende Einstiegspunkt für (nun auch sinnvoller benamte) Logik-Autotool-Aufgaben dieser Link: https://git.uni-due.de/fmi/autotool-dev/-/tree/ude-latest-3/collection/src/Logic

Und etwa die Zutaten bzgl. `LogicTasks.Semantics.Decide` würden sich jetzt in https://git.uni-due.de/fmi/autotool-dev/-/blob/ude-latest-3/collection/src/Logic/Semantics/FindMistakes.hs identifizieren lassen.

**Comment by KatinkaMeer** [comment]
Okay, ich bin noch nicht sicher wie genau ich diese Information nutzen sollte, aber den Aufruf für Max.hs habe ich bereits: generate (genMaxInst dMinMaxConf) >>= \inst -> LogicTasks.Semantics.Max.description inst `withLang` German

**Comment by patritzenfeld** [comment]
@KatinkaMeer Ich habe vor kurzem die Namen der Dateien im Autotool-Repo angepasst, aber die Namen nicht im logik-tasks-Repo geändert. Daher passen die Namen jetzt nicht mehr wirklich zusammen.
Das sollte aber nicht weiter schlimm sein. Die Aufgabentexte werden immer mit der gleichen Funktion `description` erstellt. Also sollten sich alle Texte mit einem ähnlichen Aufruf anzeigen lassen, z.B. für die Resolutionsaufgabe (Resolve.hs)
`generate (genResInst dResConf) >>= \inst -> LogicTasks.Semantics.Resolve.description inst withLang German`.

Die gen-Funktionen und Default-Configs heißen eigentlich immer genau wie die Datei, also `genFillInst`, `dFillConf` für die Fill-Aufgabe, etc. Einzige Ausnahme ist die `dMinMaxConf`, die für Max und Min benutzt wird.
