### ISSUE TITLE
Wieso ~ für die Negation?

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#49]
In Max, Min, Step müssen Formeln angegeben werden, dabei wird ~ für die Negation gefordert.
Wieso nicht - ?
Das wäre sowohl intuitiver als auch einfacher einzugeben.

**Comment by jvoigtlaender** [comment]
Hmm, da bin ich mir nicht sicher. Zum einen sieht `-` eben nach Minus aus, und könnte Neulinge eher verwirren durch "Verwechslung" logischer mit arithmetischen Operationen. Die Idee des `~` ist sicher, dass es ein Stück weit wie 
![image](https://github.com/fmidue/logic-tasks/assets/5853832/e8c8eb7c-f68b-4bc6-a6cf-a2981c2925e7)
 aussieht.

**Comment by jvoigtlaender** [comment]
Andererseits scheint etwa Prover9, den wir vielleicht irgendwann mal zur Demonstration in der Lehrveranstaltung benutzen werden, und uns also an dessen Eingabesprache orientieren könnten, tatsächlich `-` für logische Negation zu benutzen.

In Prolog wird `\+` als Symbol für logische Negation genutzt.

@owestphal, was denkst du?

**Comment by jvoigtlaender** [comment]
Prover9 syntax: 
![image](https://github.com/fmidue/logic-tasks/assets/5853832/079612af-0e3c-44c4-9a4c-6ebdee8e0602)

**Comment by owestphal** [comment]
Prinzipiell finde ich `~` am Besten, auch weil es durch kein bekanntes Konzept überladen ist.

Es muss natürlich nicht nur eine Möglichkeit geben. Es könnte ja zum Beispiel sowohl `~` also auch `nicht` und `not` zulässig sein.

Siehe auch [erster Google-Treffer für "truth table generator"](https://web.stanford.edu/class/cs103/tools/truth-table-tool/) :)

**Comment by KatinkaMeer** [comment]
Finde `not` auch gut.
