### ISSUE TITLE
Eingabeformat für Resolution

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#5]
Analog zu Resolution auf Papier sollte die Eingabe über Mengenschreibweise erfolgen.

Format Vorschlag: `({A,~B,C};{B,D};{A,C,D})` wobei `{}` für die leere Klausel verwendet werden muss.
_Trennung von Literalen durch `,` und von Tripel Komponenten durch `;`!_ 

Darüber hinaus könnte es zur Vermeidung von Schreib- bzw. Kopierarbeit eine Möglichkeit geben Klauseln per Id zu referenzieren.
Z.B. durch _(optionale)_ Nummerierung der Klauseln: `[({A,~B,C};{B,D};{A,C,D}=5), ({~C},5,{A,D}=6),...]` wobei auch die initialen Klausen Nummern bekommen sollten, die geeignet kommuniziert werden sollten.  

**Grundsätzlicher Leitfaden für das Eingabeformat sollte sein, dass die von der Aufgabe getestete Fähigkeit Anwendung der Resolution ist, und nicht die korrekte Eingabe eines Lösungskandidaten :smile:.**

**Comment by jvoigtlaender** [comment]
@owestphal, warum die Unterscheidung zwischen Kommas und Semikolons? Auf den Vorlesungsfolien mache ich ein explizites Argument dazu, warum es okay ist, in der Mengenschreibweise von KNFs (für Resolution) sowohl "innen" als auch "außen" Kommas zu nehmen, also da sowohl Disjunktion als auch Konjunktion durch Kommas zu ersetzen. Vielleicht ist es schade, dies sich dann bei den Übungsaufgaben doch nicht zu "trauen".

(Und ein anderer Punkt wäre: Dein konkreter Vorschlag ersetzt jetzt Konjunktion durch Semikolon und Disjunktion durch Komma. Das könnte insofern später für Verwirrung sorgen als es in Prolog dann genau umgekehrt ist: Komma ist "und", Semikolon ist "oder".)

**Comment by owestphal** [comment]
Die Idee war, Fehler bei Trennzeichen einfach optisch finden zu können (aus Studierenden Sicht). Das Prolog Argument ist allerdings richtig. Das sollte nicht vermischt werden.

Dann vielleicht doch besser einfach überall Kommas.

**Comment by patritzenfeld** [comment]
Eingabe ist jetzt so umgesetzt wie im ersten Kommentar gefordert, aber nur mit ',' als Trennzeichen.

**Comment by jvoigtlaender** [comment]
Sorry, fällt mir erst jetzt auf: Sind die Klammern auch verschieden für "innen" und "außen"?

Damit es wirklich der Vorlesung entspricht, sollten alles geschweifte Klammern sein: 
![image](https://user-images.githubusercontent.com/5853832/135493975-5e27683e-69da-4bce-8c3d-b488aed76bca.png)
