### ISSUE TITLE
Verständigkeit Fehlerhinweise: "mindestens eine Änderung"

### ISSUE THREAD

**Issue by KatinkaMeer** [fmidue/logic-tasks#50]
https://github.com/fmidue/logic-tasks/blob/master/src/LogicTasks/Semantics/Decide.hs#L85
und in Fill.hs

"Es muss mindestens eine Änderung geben." hat inhaltlich eine andere Bedeutung als, das englische: "At least one mistake has to be specified." und könnte so verstanden werden, als ob man min. eine Sache an der gegebenen Antwort ändern muss.

Wie wäre es mit einer Formulierung wie: Es muss mindestens ein Fehler aufgezeigt werden.

**Comment by jvoigtlaender** [comment]
Das könnte wieder ein Fall sein ( `verifyStatic`), wo für den Änderungsbedarf entscheidend ist, an wen diese Meldung eigentlich adressiert ist (Lehrende, die eine Aufgabe konfigurieren, oder Studierende, die eine Aufgabeninstanz lösen).
