### ISSUE TITLE
Klauseln in Prolog Syntax sollten immer Hornklauseln sein

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#54]
Bei Resolution von Klauseln in "Prolog Notation" werden aktuell beliebige Klauseln generiert (siehe Beispiel).
Das könnte verwirrend für Studierende sein, da in der Praxis ja immer Hornklauseln vorliegen. 

![2023-10-16_16-03](https://github.com/fmidue/logic-tasks/assets/10613418/04b3aa0f-68bf-49ec-bd1b-7091856d2c9c)

**Comment by jvoigtlaender** [comment]
Will be handled in #72.
