### ISSUE TITLE
Alternative Syntax in Prolog Klauseln

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#55]
Sollten Ausdrücke wir `-f(a)` oder `~f(a)` als Prolog Literale aktzeptiert werden?

**Comment by jvoigtlaender** [comment]
Ja, sofern `-` und `~` auch andernorts als Alternativen zum Negationszeichen akzeptiert werden.

In den Folien gibt es ja zum Beispiel dies im Prolog-Kontext: 
![image](https://github.com/fmidue/logic-tasks/assets/5853832/11b1018c-e91f-4998-adaf-06068b40cbde)
also auch das symbolische Negationszeichen statt eigentlichem Schlüsselwort `not` aus Prolog.

**Comment by jvoigtlaender** [comment]
Die nächste Frage, die sich dann stellt, ist wahrscheinlich, ob auch wie in Prolog der Operator `\+` akzeptiert werden sollte.
