### ISSUE TITLE
Parser-Rückmeldung:

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#59]
Hier: 
![image](https://github.com/fmidue/logic-tasks/assets/5853832/f77eedfa-3bd3-4443-af57-5a1902a1abf7)
ist für Studierende wahrscheinlich das Feedback nicht sehr hilfreich.

Analog etwa auch hier: 
![image](https://github.com/fmidue/logic-tasks/assets/5853832/ed7e5bbe-2a10-445f-8e97-8e73d35f5ba7)
Der "eigentliche Fehler" ist ja, dass da am Ende etwas fehlt (also etwa `A /\ B` würde zumindest geparset, egal ob es nun die richtige Antwort ist oder nicht), nicht dass `/\` als Operatorzeichen falsch wäre.

**Comment by owestphal** [comment]
see 16f12b35de51fac078789e7ba8764b36e1e48812 and fccdddb929bfc089fcc6dd0bd413f72199a80f72

**Comment by jvoigtlaender** [comment]
Closing, then?
