### ISSUE TITLE
Unicode-Pfeile?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#61]
Für `/\` etc. scheint ja Ein- und Ausgabe jetzt (durchgängig?) auch mit Unicode-Symbolen zu gehen.

Ist das auch für `=>`, `<=`, `<=>` möglich?

**Comment by owestphal** [comment]
Prinzipiell ja, hatte ich aber nicht gemacht, weil die verfügbaren Symbole das lesen eher schwieriger machen, meiner Meinung nach.
Das einzige Zeichen für die Biimplikation ist z.B. das sehr kleine Zeichen ⇔. In einer Formel sieht das sehr seltsam aus:
![2023-11-09_11-51](https://github.com/fmidue/logic-tasks/assets/10613418/a2820e92-b589-4171-b5be-545c0fb0ae56)

(das Leerzeichen hinter ⇔ ist nicht Teil des Symbols. Ohne das Leerzeichen wird ⇔ im Terminal allerdings von den nachfolgenden Zeichen zur Hälfte verdeckt.)
