### ISSUE TITLE
Unerwartete Fehler bei Eingaben mit Leerzeichen

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#7]
Bei Eingaben wie dieser würde ich eigentlich keinen Fehler erwarten.

![image2](https://user-images.githubusercontent.com/10613418/135605647-2130c2db-0978-41b8-a602-c75ab77d90ab.png)

**Comment by patritzenfeld** [comment]
Whitespace-Parsing wurde generell überarbeitet und sollte jetzt für alle Aufgaben wie zu erwarten funktionieren.
