### ISSUE TITLE
Tabellenkopf für Wahrheitstafeln

### ISSUE THREAD

**Issue by owestphal** [fmidue/logic-tasks#8]
"F=" führt hier nicht nur zu einer unschönen Verschiebung der Trennelemente, man könnte auch annehmen, dass die Formel F die Disjunktion von A,C,D und F ist. (Z.B. wenn man  `|` als Operator für die Disjunktion aus diversen Programmiersprachen kennt)

![image](https://user-images.githubusercontent.com/10613418/135605911-cc58a6d0-34f9-4c03-8c61-b75fb675f140.png)

**Comment by patritzenfeld** [comment]
Copy-Paste-Fehler wurde entfernt.
