### ISSUE TITLE
problematische Parser-Rückmeldungen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#83]
Zum Beispiel hierzu, bei einer geforderten `TreeFormulaAnswer`:
```
C ∧ (¬ D ∧ B) ∧ (¬ A ∨ E)
```
kommt die Fehlermeldung
```
C ∧ (¬ D ∧ B) ∧ (¬ A ∨ E)
..............^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

falsches Zeichen: '\8743'
möglich ist hier: space oder end of input
------------------------------------------------------------------------
```
Mal davon abgesehen, dass es sicher netter wäre, wenn auch in den Fehlermeldungen die Unicode-Symbole verwendet würden, ist das eigentliche Problem hier eins der Klammerung. Denn folgendes würde als korrekt geformte Eingabe akzeptiert:
```
(C ∧ (¬ D ∧ B)) ∧ (¬ A ∨ E)
```
Die Fehlermeldung `möglich ist hier: space oder end of input` hilft diesbezüglich aber überhaupt nicht auf die Sprünge.

Zwei mögliche Lösungen (die zweite davon hat weitere didaktische Aspekte):
- Parser ändern, so dass oben eine andere Fehlermeldung kommt. Und sei es einfach ein allgemeines (bei allen Fehlermeldungen des Parsers) "Vielleicht haben Sie irgendwelche Klammern vergessen?"
- Beim Einlesen einer `TreeFormulaAnswer` das Weglassen von Klammern (gemäß Assoziativität) zulassen, also nicht mit Syntaxfehler zurückweisen, aber dann bei der semantischen Bewertung das als Fehler zählen. So war der Aufgabentyp ursprünglich mal, noch im letzten Durchgang, vor Commit bcbacceca1bc7cb2be7d8a62046797ed3c3eddcb (denke ich).

**Comment by owestphal** [comment]
Ich hatte mich vor Weihnachten schon mal daran versucht, das Problem zu lösen. Prinzipiell ist das auch keine große Sache. Der `UniversalParser` ist nach den Prinzipien in [Design Patterns for Parser Combinators](https://dl.acm.org/doi/pdf/10.1145/3471874.3472984) aufgebaut. Entsprechend könnte das Problem durch einen zusätzlichen Fehlercontextparser behoben werden (siehe Pattern 4b im Paper):
```haskell
noFixity :: Parser NoFixity
noFixity = do
  x <- basic
  NoFixity x <$> anyBinaryOp <*> basic <* _noOperator <|> pure (OfBasic x)

_noOperator :: Parser ()
_noOperator =
  notFollowedBy (andParser <|> orParser <|> implicationParser <|> biImplicationParser)
  <|> unexpected (Label $ NonEmpty.fromList "operator (perhaps you are missing some parentheses)")
```
anstatt
https://github.com/fmidue/logic-tasks/blob/57981621e477ee5400bc19821e634149d5547b12/src/UniversalParser.hs#L172-L175

Das Problem ist allerdings, dass dieses Pattern aufgrund von Eigenheiten in der `Parsec` Implementierung nicht funktioniert. Ich hatte ein Experiment mit `Megaparsec` gemacht, und da gibt es dann für das Beispiel oben den etwas hiflreicheren Fehler
```
1:15:
  |
1 | C ∧ (¬ D ∧ B) ∧ (¬ A ∨ E)
  |               ^
unexpected operator (perhaps you are missing some parentheses)
expecting white space
```
(Das expecting whitespace bekommt man sicher auch noch weg)

Leider ist `Parsec` aber sehr tief im Autotool verankert, sodass wir für die Aufgabe nicht einfach zu `Megaparsec` wechseln können. Auch wenn das aus meiner Sicht nach dieser Erfahrung sinvoll wäre.

**Comment by owestphal** [comment]
Das Problem mit dem Vorschlag ist, dass wir von Seiten der Aufgaben, den Parser nie aktiv aufrufen. Das macht Autotool für uns. Daher können wir auch nicht einfach zwei Parser hintereindander aufrufen und die Ergebnisse vergleichen. Beider Parser müssten also in einem Parser mittels `<|>` kombiniert werden. Dann ist allerding das Zurecht-Basteln der Fehlermeldungen nicht so ohne weiteres möglich. Wieder aufgrund von `Parsec`, das keine  konditionale oder generell komplexere über `String`-Fehler-Messages hinaus gehende Fehlerbehandlung erlaubt.
(Laut `Megaparsec`'s Dokumentation bestünde dort die Möglichkeit: "Megaparsec allows us to conditionally process parse errors inside a running parser")

**Comment by jvoigtlaender** [comment]
Ich verstehe nicht, warum nicht folgendes möglich ist (konzeptionell so ähnlich war es im Grunde ursprünglich in der Bachelorarbeit):
- der zu parsende Eingabetyp für die betreffenden Aufgabentypen ist einfach nur `String`
- also jede Texteingabe wird akzeptiert
- in `partialGrade` wird dann (vor irgendwelchen anderen Überprüfungen) geparset
- dabei besteht volle Kontrolle darüber, welche Parser in welcher Reihenfolge aufgerufen werden und was mit ihren Fehlermeldungen passiert etc.

**Comment by owestphal** [comment]
Ja okay, das geht natürlich. Dann müssen wir aber eigentlich auch nicht diesen Umweg gehen, und können `Parsec` einfach durch `Megaparsec` ersetzen.

**Comment by owestphal** [comment]
Grundsätzliche Architektur umgestetzt durch #125
