### ISSUE TITLE
Syntax in Resolutionsaufgaben zur Aussagenlogik

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#84]
In https://github.com/fmidue/logic-tasks/issues/56#issuecomment-1765950712 vermutete ich, da würde (nur) Mengenschreibweise genutzt. Das Gegenteil scheint der Fall zu sein, zumindest für einige Resolutionsaufgaben:

![image](https://github.com/fmidue/logic-tasks/assets/5853832/7f6be5f2-9466-47e3-b4be-bb495e2b2c5b)

Als Resolvente könnte man sich ja auch `{not B, C}` statt `not B or C` vorstellen.

Dann wohl auch in der Aufgabenstellung selbst.

Vielleicht durch eine Konfigurationsoption steuerbar.

**Comment by jvoigtlaender** [comment]
Kleinere "Ungereimtheiten" im Beispiel oben:
- In der Legende wird nicht `not` als Darstellungsoption für die Negation angeführt, dennoch scheint es zu gehen.
- Was ist hier mit Unicode-Eingaben?

**Comment by owestphal** [comment]
> In der Legende wird nicht not als Darstellungsoption für die Negation angeführt, dennoch scheint es zu gehen.

Das ist im Moment von der Sprache abhängig. In deutschen Aufgabenstellungen sind `nicht`, `und`, `oder` in der Legende und auf Englisch entsprechend `not`, `and`, `or`. Der Parser selbst kümmert sich darum allerdings nicht und erlaubt immer alles.

> Was ist hier mit Unicode-Eingaben?

Unicode hatte ich absichtlich nicht in die Legenden geschreiben (bei allen Aufgaben), weil ich angenommen habe, dass die Symbole dann sowieso nur durch copy-paste benutzt werden würden. Und so ein Vorgehen sollte ja eigentlich durch die Erweiterung der Darstellungsmöglichkeiten vermieden werden. (Man kann natürlich auch argumentieren, dass dann `\/` und `/\` auch nicht angezeigt werden sollten)

**Comment by jvoigtlaender** [comment]
Bzgl. der Spracheinstellung und ihrer Auswirkung: macht Sinn.

**Comment by jvoigtlaender** [comment]
Bzgl. des Anzeigens von Unicode: Das kam mir gar nicht in den Sinn, dass man vielleicht vermeiden möchte, dass zu viel copy-pasted wird, weil die Studierenden erstmal händisch Syntax eingeben "lernen" sollen.

Ich meine sogar gesehen zu haben, dass irgendwo in einem Aufgabentext mal explizit aufgefordert wird, zu kopieren und editieren. Bei der Klammer-Entfernen-Aufgabe?

Vielleicht ist es am besten, das konfigurierbar zu halten. Also ein Flag `offerUnicodeInput` bei allen relevanten Aufgabentypen. Wenn dieses auf `True` gesetzt ist, werden in den Legenden auch die Unicode-Symbole mit angezeigt.

**Comment by jvoigtlaender** [comment]
Wie in https://github.com/fmidue/logic-tasks/issues/86#issue-2088043114 müsste gegebenenfalls die Legende angepasst werden, wenn hier Eingabe (nur) als Mengennotation eingeführt würde.
