### ISSUE TITLE
irreführende Eingabe-Legende

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/logic-tasks#86]
Bei der Resolutionsschritt-Aufgabe enthält die Aufgabenstellung dies:

![image](https://github.com/fmidue/logic-tasks/assets/5853832/be8cbd75-ac81-4981-be01-b89c365b912f)

Also `\/` und `oder` werden als "mögliche Schreibweisen" genannt, aber in Wirklichkeit wird **nicht** akzeptiert, wenn etwa `{A, nicht B}` als `{A oder nicht B}` oder `A oder nicht B` geschrieben wird.

Sprich, es gibt hier keine sinnvolle Möglichkeit, `\/` oder `oder` in der Lösungseingabe zu verwenden. Der Erklärtext suggeriert aber anderes.

**Comment by nimec01** [comment]
Die "erlaubten" Schreibweisen bei `Oder`  zu `,` zu ändern, würde wahrscheinlich zu Verwirrung führen. Was meiner Meinung nach am sinnvollsten wäre, ist den `Oder`-Teil durch `Nicht-leere Klausel` zu ersetzen, wobei dort dann eher ein Beispiel passen würde.

Oder gibt es diesbezüglich andere Vorstellungen @jvoigtlaender ?

**Comment by jvoigtlaender** [comment]
Am besten vielleicht so ähnlich einfach (statt des `Oder`-Teils):
```
Nicht-leere Klausel:
  { ... }
```
Was für die `...` stehen darf, sollte dann eigentlich klar genug sein, da weiter unten ja auch schon das konkrete Beispiel mit `{A, nicht B}` angezeigt wird.
